### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by Vahe1994** [byungsook/vectornet#1]
Hello! 

Many thank you for tour work and for sharing this wonderful implementation. Code working nicely.
But I'm curious is there a way to make it  work with bigger images(running original code took too long even on prediction)?  

P.s. I tried to make it work for image 512x512 , but even predict on this one image take 8h (without gco) and gco takes even more time(about 3 days). Maybe I'm doing something wrong and there is a more efficient way to work with this kind of images?

**Comment by byungsook** [comment]
Thanks for your interest!
Unfortunately, I haven't considered the scalability of our method so much. Basically, predictions are done per pixel, so sampling on pixels might be an option followed by interpolating predictions between pixels. In gco stage, there is a "neighbor_sample" parameter for sparse node sampling on farther area for graph construction. For now, default value is 1 which means it makes dense graph for optimization, but you can control this parameter to speed up gco (of course, there is a somewhat trade-off). Hope it helps!

**Comment by Vahe1994** [comment]
Thank you, I'll try. 
It helps a lot :)
