### ISSUE TITLE
Is multi-class dataset not available?

### ISSUE THREAD

**Issue by naoto0804** [byungsook/vectornet#2]
I'd like to compare my method with your method on the multi-class dataset. However, when I downloaded the dataset you provide ([here](http://www.byungsoo.me/project/vectornet/qdraw.7z)), I found that it only contains `cat` and `baseball`. 
Is it possible to share `chandelier`, `elephant`, `backpack` and `bicycle` class for the quickdraw dataset?

P.S.
Thank you so much for fully-reproducible codes. It's easy to understand what is going on everywhere.

**Comment by byungsook** [comment]
Hi @naoto0804, thanks for your interests on this project!
I just updated the dataset to include multi.7z and added `preprocess_svg.py` to the repository, so please take a look.
If you have any questions or problems, let me know again.

**Comment by byungsook** [comment]
Hmm.. Sorry, I think I lost the original list of the test dataset.
A new test dataset is uploaded, I hope it would help.

**Comment by naoto0804** [comment]
Unfortunately, I'm still confused. Decompressed `test` folder contains 8000 images from `cat`, `chandelier`, `elephant` and `baseball`, that are the same as the categories included in the `train` folder. 
If you remember, could you tell me the number of images used for the test from `backpack` and `bicycle`, so that I can get the images by `preprocess_svg.py`?

**Comment by byungsook** [comment]
I generated and added `test_unseen` folder to the qdraw.
