### ISSUE TITLE
Hello author, how can my own pictures be vectorized with this project

### ISSUE THREAD

**Issue by 1020433727** [byungsook/vectornet#5]
After I trained the network, I found that the test folder still needs the svg format vector graphics for segmentation, so I want to ask how to use the network to vectorize my pictures。

**Comment by 1020433727** [comment]
For example, I have a jpg line drawing, how to use this project to separate the lines

**Comment by byungsook** [comment]
Hi, the current code calls `read_svg` to load a test image as follows:

https://github.com/byungsook/vectornet/blob/d92983c74e7c1f0ec3725c3bcb7bfa83ab45fadc/tester.py#L145

The latter two outputs are required for debugging or computing accuracy, so you can change this line to load your own test image.

You might need to change the following function as well (e.g., skip step3):

https://github.com/byungsook/vectornet/blob/d92983c74e7c1f0ec3725c3bcb7bfa83ab45fadc/tester.py#L394-L434

The following code in `save_label_img()` will vectorize the result image by running potrace executable:

https://github.com/byungsook/vectornet/blob/d92983c74e7c1f0ec3725c3bcb7bfa83ab45fadc/tester.py#L624-L628

**Comment by 1020433727** [comment]
Hi, I am very glad to receive your reply. The project uses read_svg to read the picture. If I want to test a jpg image, do I need to convert the image to a svg format vector image before segmentation?  Is the entire process svg-> png-> svg?
