### ISSUE TITLE
Training datasets are unattainable.

### ISSUE THREAD

**Issue by Wenretium** [byungsook/vectornet#6]
Hello author, links of the training datasets in README seem to be invalid. I click in and jump to the Page not found page. Hope you can provide it again. Thanks!

**Comment by byungsook** [comment]
Now it's fixed!

**Comment by ningyuv** [comment]
Hi, links of the training datasets in README seem to be invalid again. It shows "cannot download file" after "connecting". Hope you can provide it again. Thanks!
